version: '3.8'

services:
  flask_service:
    build: ./service-flask
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  node_service:
    build: ./service-node
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
